apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elastic-connector.fullname" . }}
  labels:
    {{- include "elastic-connector.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    camel.component.kafka.brokers={{ .Values.kafka.bootstrapServer }}
    {{ if .Values.kafka.securityProtocol -}}
    camel.component.kafka.security-protocol=SASL_SSL
    {{ end -}}
    {{ if .Values.kafka.saslMechanism -}}
    camel.component.kafka.sasl-mechanism=PLAIN
    {{ end -}}
    {{ if eq .Values.kafka.saslMechanism "PLAIN" -}}
    camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ .Values.kafka.userId }}" password="{{ .Values.kafka.password }}";
    {{- end }}

    kafka.product.topic.name={{ .Values.kafka.topics.product }}
    kafka.product.consumer.group={{ .Values.kafka.consumerGroup }}

    quarkus.elasticsearch.hosts={{ .Values.elasticsearch.hosts }}
    quarkus.elasticsearch.username={{ .Values.elasticsearch.username }}
    quarkus.elasticsearch.password={{ .Values.elasticsearch.password }}
    quarkus.elasticsearch.protocol={{ .Values.elasticsearch.protocol }}

    elasticsearch.index.name={{ .Values.elasticsearch.index }}
