apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cashback-connector.fullname" . }}
  labels:
    {{- include "cashback-connector.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    camel.component.kafka.brokers={{ .Values.kafka.bootstrapServer }}
    {{ if .Values.kafka.securityProtocol -}}
    camel.component.kafka.security-protocol=SASL_SSL
    {{ end -}}
    {{ if .Values.kafka.saslMechanism -}}
    camel.component.kafka.sasl-mechanism=PLAIN
    {{ end -}}
    {{ if eq .Values.kafka.saslMechanism "PLAIN" -}}
    camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ .Values.kafka.userId }}" password="{{ .Values.kafka.password }}";
    {{- end }}

    quarkus.datasource.cashback.jdbc.url=jdbc:postgresql://{{ .Values.postgresql.host }}:5432/{{ .Values.postgresql.database }}
    quarkus.datasource.cashback.username={{ .Values.postgresql.username }}
    quarkus.datasource.cashback.password={{ .Values.postgresql.password }}

    kafka.customer.topic.name={{ .Values.kafka.topics.customer }}
    kafka.customer.consumer.group={{ .Values.kafka.consumerGroup }}

    kafka.sale_aggregated.topic.name={{ .Values.kafka.topics.saleAggregated }}
    kafka.sale_aggregated.consumer.group={{ .Values.kafka.consumerGroup }}

    kafka.expense_event.topic.name={{ .Values.kafka.topics.expenseEvent }}
