apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafdrop.fullname" . }}
  labels:
    {{- include "kafdrop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafdrop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafdrop.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kafdrop.serviceAccountName" . }}
      serviceAccount: {{ include "kafdrop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKERCONNECT
              value: {{ .Values.kafka.bootstrapServer }}
            - name: KAFKA_PROPERTIES
            - name: KAFKA_TRUSTSTORE
            - name: KAFKA_KEYSTORE
            - name: JVM_OPTS
            - name: JMX_PORT
              value: '8686'
            - name: HOST
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /
            - name: KAFKA_PROPERTIES_FILE
              value: /config/kafka.properties
            - name: KAFKA_TRUSTSTORE_FILE
            - name: KAFKA_KEYSTORE_FILE
            - name: SERVER_PORT
              value: '{{ .Values.ports.httpPort }}'
            - name: CMD_ARGS
            - name: SCHEMAREGISTRY_CONNECT
            - name: SCHEMAREGISTRY_AUTH            
          ports:
            - name: {{ .Values.ports.httpPortName }}
              containerPort: {{ .Values.ports.httpPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: kafka-properties
              mountPath: /config
      volumes:
        - name: kafka-properties
          secret:
            secretName: {{ include "kafdrop.fullname" . }}
            defaultMode: 420
