apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafdrop.fullname" . }}
  labels:
    {{- include "kafdrop.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  kafka.properties: |-
    {{ if .Values.kafka.securityProtocol -}}
    security.protocol=SASL_SSL
    {{ end -}}
    {{ if .Values.kafka.saslMechanism -}}
    sasl.mechanism=PLAIN
    {{ end -}}
    {{ if eq .Values.kafka.saslMechanism "PLAIN" -}}
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="{{ .Values.kafka.userId }}" \
        password="{{ .Values.kafka.password }}";
    {{ end -}}
