{{- if .Values.authentication.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authentication.secret }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-connect.argocd-syncwave" . | nindent 4 }}
stringData:
  client-id: {{ .Values.authentication.username }}
  {{ .Values.authentication.passwordKey }}: {{ .Values.authentication.password }}
type: Opaque
{{- end }}
