apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ include "kafka-connect.name" . }}
  annotations:
    {{- include "kafka-connect.annotations" . | nindent 4 }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  version: {{ .Values.version }}
  replicas: {{ .Values.replicas }}
  bootstrapServers: {{ .Values.bootstrapServers }}
  config:
    group.id: {{ include "kafka-connect.name" . }}
    offset.storage.topic: '{{ .Values.topicPrefix }}.{{ include "kafka-connect.name" . }}-offsets'
    config.storage.topic: '{{ .Values.topicPrefix }}.{{ include "kafka-connect.name" . }}-configs'
    status.storage.topic: '{{ .Values.topicPrefix }}.{{ include "kafka-connect.name" . }}-status'
    key.converter: {{ .Values.keyConverter }}
    value.converter: {{ .Values.valueConverter }}
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: {{ .Values.replicationFactor }}
    offset.storage.replication.factor: {{ .Values.replicationFactor }}
    status.storage.replication.factor: {{ .Values.replicationFactor }}
    topic.creation.enable: true
    default.replication.factor: {{ .Values.replicationFactor }}
  {{- if .Values.authentication.enabled }}
  authentication:
    passwordSecret:
      password: {{ .Values.authentication.passwordKey }}
      secretName: {{ .Values.authentication.secret }}
    username: {{ .Values.authentication.username }}
    type: {{ .Values.authentication.type }}
  {{- end }}
  {{- if .Values.tls }}
  tls:
    trustedCertificates: []
  {{- end }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  livenessProbe:
    {{- toYaml .Values.livenessProbe | nindent 4 }}
  readinessProbe:
    {{- toYaml .Values.readinessProbe | nindent 4 }}
  jvmOptions:
    gcLoggingEnabled: false
  build:
    output:
      type: imagestream
      image: {{ include "kafka-connect.build.imageStream" . }}:latest
    plugins:
      {{- toYaml .Values.build.plugins | nindent 6 }}
