apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "kafka-connect.build.imageStream" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-connect.argocd-syncwave" . | nindent 4 }}
