fullnameOverride: sales-streams

replicaCount: 1

image: 
  repository: quay.io/solution-pattern-cdc/sales-streams
  imagePullPolicy: IfNotPresent
  tag: "facb2c4"

serviceAccount:
  create: true

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

kafka:
  bootstrapServer: kafka-kafka-bootstrap:9092
  securityProtocol: ""
  saslMechanism: ""
  userId: ""
  password: ""
  streams:
    topics: retail.updates.public.sale,retail.updates.public.line_item,retail.sale-aggregated
    replicationFactor: 2
    commitIntervalMs: 10000
    applicationId: retail
  topics:
    saleChangeEvent: retail.updates.public.sale
    lineItemChangeEvent: retail.updates.public.line_item
    aggregatedSale: retail.sale-aggregated
