apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "retail-db.labels" . | nindent 4 }}
  name: {{ include "retail-db.fullname" . }}
  annotations:
    {{- include "retail-db.argocd-syncwave" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    {{- include "retail-db.selectorLabels" . | nindent 4 }}
