fullnameOverride: search-service

replicaCount: 1

image: 
  repository: quay.io/solution-pattern-cdc/search-service
  imagePullPolicy: Always
  tag: "bdd446e"

serviceAccount:
  create: true

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

elasticsearch:
  hosts: 
  username: 
  password: 
  protocol: http
  index: products
