version: 3.3.1
replicas: 1
bootstrapServers: 
topicPrefix: retail
keyConverter: org.apache.kafka.connect.json.JsonConverter
valueConverter: org.apache.kafka.connect.json.JsonConverter
replicationFactor: 1
authentication:
  enabled: true
  secret: kafka-service-account
  passwordKey: client-secret
  username:
  password:
  type: plain
tls: true
resources:
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 1Gi
livenessProbe:
  initialDelaySeconds: 45
  timeoutSeconds: 5
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
build:
  output:
    type: imageStream
    image: kafka-connect-build:latest
  plugins:
    - name: debezium-postgres-connector
      artifacts:
        - type: tgz
          url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.9.7.Final/debezium-connector-postgres-1.9.7.Final-plugin.tar.gz
          sha512sum: 088a92a7456101d7f01e356250439728e2018355d11797f20b8520d58ba6ce4400f917263223386b031c000d21010e1387970707bd7e8f92a681ac3c88ccc38b

argocd:
  enabled: false
  syncwave: ""
