fullnameOverride: cashback-connector

replicaCount: 1

image: 
  repository: quay.io/solution-pattern-cdc/cashback-connector
  imagePullPolicy: IfNotPresent
  tag: "83f8e65"

serviceAccount:
  create: true

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

kafka:
  bootstrapServer: kafka-kafka-bootstrap:9092
  securityProtocol: ""
  saslMechanism: ""
  userId: ""
  password: ""
  topics:
    customer: retail.updates.public.customer
    saleAggregated: retail.sale-aggregated
    expenseEvent: retail.expense-event
  consumerGroup: cashback-connector

postgresql:
  host: cashback-db
  username: cashback
  password: cashback
  database: cashback
  
