clusterName: retail
version: 7.17.2

auth:
  fileRealm:
    - secretName: elastic-user-secret

credentials:
  username: cashback
  password: cashback
  roles: superuser

http:
  service: {}
  tls:
    certificate: {}
    selfSignedCertificate:
      disabled: true  

nodeSets:
  name: default
  count: 1
  config:
    node.store.allow_mmap: false

index: 
  name: products
  config:
    {
      "settings": {
        "index": {
          "number_of_shards": 1,
          "number_of_replicas": 0
        }
      },
      "mappings": {
          "properties": {
              "description": {
                  "type": "text"
              },
              "name": {
                  "type": "text"
              }
          }
      }
    }

configJob:
  name: es-config-job

argocd:
  enabled: false
  syncwave: ""
