fullnameOverride: cashback-service-ui

replicaCount: 1

image: 
  repository: quay.io/solution-pattern-cdc/cashback-service-ui
  imagePullPolicy: IfNotPresent
  tag: "c73a39b"

serviceAccount:
  create: true

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

postgresql:
  host: ""
  username: ""
  password: ""
  database: ""

pageSize: 15
