apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.configJob.name }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- include "elasticsearch.argocd-syncwave" . | nindent 4 }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{ .Values.configJob.name }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-elasticearch
          image: registry.redhat.io/rhel8/support-tools:8.5
          command:
            [
              "sh",
              "-c",
              "for i in $(seq 1 300); do nc -zvw1 {{ .Values.clusterName }}-es-http 9200 && exit 0 || sleep 3; done; exit 1",
            ]
      containers:
        - name: {{ .Values.configJob.name }}
          image: registry.redhat.io/rhel8/support-tools:8.5
          env:
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clusterName }}-es-elastic-user
                  key: elastic
          command:
            - /bin/sh
            - -c
            - |
              curl -v -u elastic:$ELASTICSEARCH_PASSWORD -X PUT http://{{ .Values.clusterName }}-es-http:9200/{{ .Values.index.name }} -H 'Content-Type: application/json' -d '
              {{ .Values.index.config | toJson }}
              '
