apiVersion: v1
kind: Secret
metadata:
  name: elastic-user-secret
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- include "elasticsearch.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  username: cashback
  password: cashback
  roles: superuser
