apiVersion: v1
kind: Secret
metadata:
  name: elastic-user-secret
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- include "elasticsearch.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
  roles: {{ .Values.auth.roles }}
