apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cashback-service-ui.fullname" . }}
  labels:
    {{- include "cashback-service-ui.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    default_page_size={{ .Values.pageSize }}
    quarkus.datasource.jdbc.url=jdbc:postgresql://{{ .Values.postgresql.host }}:5432/{{ .Values.postgresql.database }}
    quarkus.datasource.username={{ .Values.postgresql.username }}
    quarkus.datasource.password={{ .Values.postgresql.password }}
