apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-simulation.fullname" . }}
  labels:
    {{- include "retail-simulation.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    quarkus.datasource.username={{ .Values.postgresql.username }}
    quarkus.datasource.password={{ .Values.postgresql.password }}
    quarkus.datasource.jdbc.url=jdbc:postgresql://{{ .Values.postgresql.host }}:5432/{{ .Values.postgresql.database }}
