apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "cashback-db.labels" . | nindent 4 }}
    app.openshift.io/runtime: postgresql    
  name: {{ include "cashback-db.fullname" . }}
  annotations:
    {{- include "cashback-db.argocd-syncwave" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cashback-db.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "cashback-db.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cashback-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "cashback-db.fullname" . }}
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cashback-db.fullname" . }}
                  key: database-password
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cashback-db.fullname" . }}
                  key: database-admin-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "cashback-db.fullname" . }}
                  key: database-name
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if eq .Values.persistence.mode "persistent" }}
          volumeMounts:
            - name: "{{ include "cashback-db.fullname" . }}-data"
              mountPath: "/var/lib/pgsql/data"
              volumes:
          {{- end }}
      {{- if eq .Values.persistence.mode "persistent" }}
      volumes:
        - name: "{{ include "cashback-db.fullname" . }}-data"
          persistentVolumeClaim:
            claimName: {{ include "cashback-db.fullname" . }}
      {{- end }}
