apiVersion: v1
kind: Secret
metadata:
  name: {{ include "search-service.fullname" . }}
  labels:
    {{- include "search-service.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    quarkus.elasticsearch.hosts={{ .Values.elasticsearch.hosts }}
    quarkus.elasticsearch.username={{ .Values.elasticsearch.username }}
    quarkus.elasticsearch.password={{ .Values.elasticsearch.password }}
    quarkus.elasticsearch.protocol={{ .Values.elasticsearch.protocol }}

    elasticsearch.index.name={{ .Values.elasticsearch.index }}
